version: "3"
services:
  music_bot:
    image: discordmusicbot
    container_name: "DiscordMusicBot"
    restart: "always"
    links:
      - postgres:postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: $db_username
      POSTGRES_PASSWORD: $db_password
      POSTGRES_DB: $db_database
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
