version: "3"
services: 
    music_bot:
        image: DiscordMusicBot
        container_name: "DiscordMusicBot"
        restart: "always"
        # volumes: 
        #     - ./log:/usr/src/app/persist.json
        links:
            - postgres:postgres
        depends_on: 
            - postgres
    postgres:
        image: postgres
        # ports: 
        #     - 5434:5432
        environment: 
            POSTGRES_USER: $db_username
            POSTGRES_PASSWORD: $db_password
            POSTGRES_DB: $db_database
        volumes: 
            - ./db:/var/lib/postgresql/data
        restart: always
